# Site Settings
title: Volodymyr Shabala
email: Volodymyr.Shabala@gmail.com
description: >
  My portfolio
baseurl: "/Portfolio"
url: "http://volodymyrshabala.github.io"
twitter_username: VolodymyrShabala
github_username:  VolodymyrShabala
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM