# Site Settings
title: Volodymyr Shabala
email: volodymyr.shabala@gmail.com
description: >
  My portfolio
baseurl: ""
url: "http://localhost:4000"
twitter_username: VolodymyrShabala
github_username:  VolodymyrShabala
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM