# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Volodymyr Shabala
email: volodymyr.shabala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Game programmer - C# - Unity - C++ - Unreal
baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: "https://volodymyrshabala.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
github_username:  VolodymyrShabala
facebook_username: volodymyr.shabala
linkedin_url: https://www.linkedin.com/in/volodymyr-shabala-84522b137/
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123

# Address information
address_city: Stockholm

# Build settings
markdown: kramdown